version = 0.1

[default.deploy.parameters]
stack_name = "event-ticketing-dev"
resolve_s3 = true
s3_prefix = "event-ticketing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev AlertEmail=you@example.com MonthlyBudgetLimit=5 EnableConfirmationEmails=true"
image_repositories = []

[prod.deploy.parameters]
stack_name = "event-ticketing-prod"
resolve_s3 = true
s3_prefix = "event-ticketing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod AlertEmail=you@example.com MonthlyBudgetLimit=10 EnableConfirmationEmails=true"
